# Generated by Django 5.2.4 on 2025-11-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0002_remove_feedback_email_remove_feedback_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='city',
            field=models.CharField(default='Unknown City', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='issue_type',
            field=models.CharField(choices=[('Pothole', 'Pothole'), ('Street Light', 'Street Light Not Working'), ('Garbage', 'Garbage Dump'), ('Drainage', 'Drainage Blockage'), ('Road Crack', 'Cracked or Damaged Road'), ('Signage', 'Missing or Damaged Sign Board'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AddField(
            model_name='feedback',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=255),
        ),
    ]
