# Generated by Django 5.2.4 on 2025-11-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0003_feedback_city_feedback_issue_type_feedback_landmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
