# Generated by Django 5.2.4 on 2025-11-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0004_alter_feedback_city_alter_feedback_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
